# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160724_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apply_acts',
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 24, 14, 24, 3, 167446, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='activity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='app.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 24, 14, 26, 23, 136483, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
