# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160724_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='activity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='app.Activity'),
        ),
    ]
