# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160726_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='status',
        ),
    ]
