# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160724_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
