# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20160727_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.ImageField(blank=True, upload_to='portrait'),
        ),
    ]
